# fly.toml app configuration file generated for renreactivities on 2023-12-31T15:59:55+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "renreactivities"
primary_region = "cdg"

[build]
  image = "racuin93/reactivities:latest"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
